[features]
seeds = false
[programs.localnet]
assignmentchecker = "6syjPkpJf6gT6JCaXvWVDfKk4vv29s16F7FTWB2t4XP5"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
