[package]
name = "program_client"
version = "0.1.0"
edition = "2018"
[dependencies.trdelnik-client]
version = "0.1"
package = "trdelnik-sandbox-client"

[dependencies.assignmentchecker]
path = "../programs/assignmentchecker"
features = ["no-entrypoint"]
